---
title: "Spatial Data Analysis"
---

## Course overview

**Course overview from GEOG 385: Spatial Data Analysis at San Diego State University**


The purpose of this course is to introduce you to methods of spatial
data analysis. The focus is on both the conceptual and applied aspects
of spatial statistical methods. We will place particular emphasis on
the computational aspects of Exploratory Spatial Data Analysis (ESDA)
methods for three diﬀerent types of spatial data: point processes,
lattice, and geostatistical. We will also cover an introduction to
regression analysis on spatially referenced data. Throughout the
course you will gain valuable hands-on experience with several
specialized software packages for spatial data analysis. The
overriding goal of the course is for you to acquire familiarity with
the fundamental methodological and operational issues in the
statistical analysis of geographic information and the ability to
extend these methods in your own research.

## Class meetings

| Meeting | Location | Time                   |
|---------|----------|------------------------|
| Lecture | [GMCS 307](https://map.concept3d.com/?id=801#!ce/12160?ct/62917,40419,40418,20161,15205,48503,54894,16202?m/611838?s/gmcs) | Tue & Thu 2:00 - 3:15pm |

## Teaching team 

| Name        | Office hours      | Location  |
|-------------|-------------------|-----------|
| [Sergio Rey](https://geography.sdsu.edu/people/bios/rey) | Thu 3:30 - 4:30pm | [PSFA 361G](https://map.concept3d.com/?id=801#!ce/12160?ct/62917,40419,40418,20161,15205,48503,54894,16202,12164?m/147097?s/) |
| Dylan Skrah | Tue 3:20-4:20pm     | Zoom      |
