---
title: "Geography 385 Spatial Data Analysis"
subtitle: "Spring 2023"
format:
  html:
    theme: cosmo 
  pdf:
    colorlinks: true
---

<hr>

## Class meetings

| Meeting | Location | Time                   |
|---------|----------|------------------------|
| Lecture | [GMCS 307](https://map.concept3d.com/?id=801#!ce/12160?ct/62917,40419,40418,20161,15205,48503,54894,16202?m/611838?s/gmcs) | Tue & Thu 2:00 - 3:15pm |

## Teaching team 

| Name                                                     | Office hours      | Location                                                                                                                      |
|----------------------------------------------------------|-------------------|-------------------------------------------------------------------------------------------------------------------------------|
| [Sergio Rey](https://geography.sdsu.edu/people/bios/rey) | [Thu 3:30 - 4:30pm (by appointment)](https://calendly.com/sjsrey/office-hours) | [PSFA 361G](https://map.concept3d.com/?id=801#!ce/12160?ct/62917,40419,40418,20161,15205,48503,54894,16202,12164?m/147097?s/) |
| Dylan Skrah                                              | Tue 3:20-4:20pm   | [PSFA 361F](https://map.concept3d.com/?id=801#!ce/12160?ct/62917,40419,40418,20161,15205,48503,54894,16202,12164?m/147097?s/) |



## Introduction

Welcome to 385: Spatial Data Analysis!


The purpose of this course is to introduce you to methods of spatial
data analysis. The focus is on both the conceptual and applied aspects
of spatial statistical methods. We will place particular emphasis on
the computational aspects of Exploratory Spatial Data Analysis (ESDA)
methods for three diﬀerent types of spatial data: point processes,
lattice, and geostatistical. We will also cover an introduction to
regression analysis on spatially referenced data. Throughout the
course you will gain valuable hands-on experience with several
specialized software packages for spatial data analysis. The
overriding goal of the course is for you to acquire familiarity with
the fundamental methodological and operational issues in the
statistical analysis of geographic information and the ability to
extend these methods in your own research.


The course takes an explicitly computational thinking
approach to its pedagogy. Students are introduced to computational
concepts and tools that are increasingly important to research that
engages with geospatial data. By adopting these tools, students
acquire a deeper engagement with, and mastery of, the substantive
concepts.

In the scope of a 15-week semester course we can only introduce a handful
of the key concepts and methods relevant to the field of spatial data analysis. As
such, the course is not intended as an exhaustive treatment. Instead,
the goal is that students will acquire an understanding of the more
common and useful methods and practices, and use the course as an entry
point for further engagement with the field.

## Prerequisites


- [GEOG 101](https://catalog.sdsu.edu/preview_course_nopop.php?catoid=5&coid=31440) or [GEOG 102](https://catalog.sdsu.edu/preview_course_nopop.php?catoid=5&coid=31442) 
- [STAT 250](https://catalog.sdsu.edu/preview_course_nopop.php?catoid=5&coid=33000) or comparable course in statistics.

All students are required to complete the [prerequisite assessment quiz](https://sdsu.instructure.com/courses/116162/quizzes/224625) before Monday 1/24 11:59pm.

## Computational Learning

We will using [open
source](https://en.wikipedia.org/wiki/Open-source_software) geospatial
software throughout the course together with [Jupyter
Notebooks](https://jupyter.org), and [Python](https://python.org) as our
scripting language.

All software for the course will be made available through
[JupyterHub](https://jupyter.org/) a web-based framework. Students
wishing to install these materials on their own machines will be given
instructions to do so, **but this is not required**.


## Readings

All required readings are available through the links listed
below. Assigned readings should be completed before the date listed in
the schedule (see below). Readings are a critical part of the
discussions we will hold in class, and therefore coming into class
prepared means having completed the readings and thought about the
content. It will be difficult to do well in this course without having
completed the readings.

| Abbrevation | Source                                                                                      |
|-------------|---------------------------------------------------------------------------------------------|
| GDS         | Rey, S.J., D. Arribas-Bel, L.J. Wolf (2023) Geographic Data Science with Python. CRC Press. |
| GSA         | de Smith, M., M.F. Goodchild, P.A. Longly (2021) Geospatial Analysis. Winchelsea Press.     |
| SAH         | de Smith, M. (2021) Statistical Analysis Handbook. Drumlin Security Ltd.                    |



## Schedule (Planned)

| Week |    Dates | Topic                                 |           Reading | Activities     |
|-----:|---------:|:--------------------------------------|------------------:|----------------|
|    1 |   Jan-19 | Introduction                          |                   |                |
|    2 |   Jan-24 | Spatial Analysis                      |     [GDS 1][gds1] | Quiz 1         |
|      |   Jan-26 | Spatial Analysis Software             |     [GDS 2][gds2] | Exercise 1 Out |
|    3 |   Jan-31 | Spatial Data                          |     [GDS 3][gds3] | Quiz 2         |
|      |   Feb-02 | Point Pattern Basics                  | [GDS 8.1][gds8.1] |                |
|    4 |   Feb-07 | Centrography                          | [GDS 8.2][gds8.2] | Quiz 3         |
|      |   Feb-09 | Point Processes                       |                   |                |
|    5 |   Feb-14 | Hands on Exercise 1                   |                   | Quiz 4         |
|      |   Feb-16 | Nearest Neighbor Methods              | [GDS 8.3][gds8.3] | Exercise 1 Due |
|      |          |                                       |                   |                |
|    6 |   Feb-21 | Area Data                             |   [GDS II][gdsii] | Quiz 5         |
|      |   Feb-23 | Visualization of Area Data            |     [GDS 5][gds5] | Exercise 2 Out |
|    7 |   Feb-28 | Spatial Autocorrelation Concepts      | [GDS 6.1][gds6.1] | Quiz 6         |
|      |   Mar-02 | Spatial Weights I                     |     [GDS 4][gds4] |                |
|    8 |   Mar-07 | Spatial Weights II                    |                   | Quiz 7         |
|      |   Mar-09 | Hands-on Exercise 2                   |                   |  Exercise 2 Due|
|    9 |   Mar-14 | Global Autocorrelation Tests          | [GDS 5.1][gds5.1] | Quiz 8         |
|      |   Mar-16 | Join Counts   I                       | [GDS 5.1][gds5.1] | Exercise 3 Out |
|   10 |   Mar-21 | Joint Counts II                       |                   | Quiz 9         |
|      |   Mar-23 | AAG (No Class)                        |                   |                |
|      | *Mar-28* | *Spring Break*                        |                   |                |
|      | *Mar-30* | *Spring Break*                        |                   |                |
|   11 |   Apr-04 | Global Autocorrelation: Moran's I     | [GDS 5.2][gds5.2] |                |
|      |   Apr-06 | Hands-on Exercise 3                   |                   | Quiz 10        |
|   12 |   Apr-11 | Local Spatial Autocorrelation         | [GDS 6][gds6]     | Exercise 3 Due, 4 Out |
|      |   Apr-13 | Project Studio                        |                   |                |
|   13 |   Apr-18 | Spatial Interpolation                 | [GSA int][gsaint] |                |
|      |   Apr-20 | Project Studio                        |                   |                |
|   14 |   Apr-25 | Spatial Networks                      | [GSA net][gsanet] |                |
|      |   Apr-27 | Hands On Exercise 4                   |                   |                |
|   15 |   May-02 | Presentations                         |                   | Exercise 4 Due |
|      |   May-04 | Presentations                         |                   |                |
|      |   May-10 | Final Examination (13:00-15:00)       |                   |                |


[gds1]: https://geographicdata.science/book/notebooks/01_geo_thinking.html
[gds2]: https://geographicdata.science/book/notebooks/02_geospatial_computational_environment.html
[gds3]: https://geographicdata.science/book/notebooks/03_spatial_data.html
[gds8.1]: https://geographicdata.science/book/notebooks/08_point_pattern_analysis.html
[gds8.2]: https://geographicdata.science/book/notebooks/08_point_pattern_analysis.html#centrography
[gds8.3]: https://geographicdata.science/book/notebooks/08_point_pattern_analysis.html#randomness-clustering
[gds9]: https://geographicdata.science/book/notebooks/09_spatial_inequality.html
[gds11]: https://geographicdata.science/book/notebooks/11_regression.html 
[gdsii]: https://geographicdata.science/book/intro_part_ii.html
[gds5]:  https://geographicdata.science/book/notebooks/05_choropleth.html
[gds6.1]:  https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html#understanding-spatial-autocorrelation
[gds4]: https://geographicdata.science/book/notebooks/04_spatial_weights.html
[gds5.1]:  https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html#binary-case-join-counts
[gds5.2]: https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html#continuous-case-moran-plot-and-moran-s-i
[gds6]: https://geographicdata.science/book/notebooks/07_local_autocorrelation.html
[gsags]: https://www.spatialanalysisonline.com/HTML/geostatistical_interpolation_m.htm?zoom_highlightsub=geostatistical
[gsakrg]: https://www.spatialanalysisonline.com/HTML/kriging_interpolation.htm 
[gsaint]: https://www.spatialanalysisonline.com/HTML/deterministic_interpolation_me.htm
[gsanet]: https://www.spatialanalysisonline.com/HTML/network_and_location_analysis.htm
[gsareg]: https://www.spatialanalysisonline.com/HTML/regression_overview.htm?zoom_highlightsub=regression
[sahmv]: https://www.statsref.com/HTML/multivariate_distributions.html?zoom_highlightsub=multivariate
[sahcor]: https://www.statsref.com/HTML/correlation.html
[sahinf]: https://www.statsref.com/HTML/simple_regression.html
[python]: http://python.org



## Grading



GEOG385 uses [specification
grading](https://www.insidehighered.com/views/2016/01/19/new-ways-grade-more-effectively-essay)
in evaluating student work and in determining your final course grade.
Your course grade will be based on the quality and quantity of the work
that you submit that is evaluated to be of an acceptable level of
quality. The acceptable level of quality demonstrates competency in the
concepts and methods covered in the course.

There is a two-step process for determination of your final course grade
at the end of the quarter:

1.  Using your quizzes, exercises, and projects, your **base grade** is
    determined.
2.  Using your final exam results, determine if your base grade includes
    a \"plus\", \"minus\", or level drop to form the course grade.

For Step 1, the base grade is determined using the following
specification:

  Level   Hurdles
  ------- -------------------------------------------------------------------------------------
  A       Pass at least 8 of 10 quizzes, earn \"Demonstrates Competency\" on 4 of 4 exercises,
          **and** submit a project that earns \"Demonstrates Competency\"
  B       Pass at least 7 of 10 quizzes, earn \"Demonstrates Competency\" on 3 of 4 exercises
  C       Pass at least 6 of 10 quizzes, earn \"Demonstrates Competency\" on 2 of 4 exercises
  D       Pass at least 5 of 10 quizzes, earn \"Demonstrates Competency\" on 1 of 4 exercises
  F       Fail to clear D-level hurdles

For Step 2, your final course grade is determined as follows:

-   If you earn at least 85% on the final exam, you will obtain a + for
    your grade. So an A base grade becomes a final A+ course grade, a B
    becomes a B+, and so on.
-   If you score between 70-85% on the final exam, your base grade
    becomes your course grade.
-   If you score between 50% and 69% on the final exam, you will obtain
    a - for your grade. So an A becomes and A-, a B becomes a B-, and so
    on.
-   If you score less than 50% on the final exam, your course grade will
    drop one level: An A base grade becomes a final B course grade.

## Quizzes

Quizzes are graded on a pass/fail basis. Starting in week two, there
will be a quiz due before each Tuesday session that pertains to the
background reading that is required before our work in class.

## Exercises

Four exercises will be introduced in class and are due in two weeks.

Each exercise is graded using a **CRN** rubric that classifies work with
marks of **C** (\"Demonstrates Competence\"), **R** (\"Needs
Revision\"), or **N** (\"Not assessable\"):

Of each exercise the following questions will be asked: Does the work
demonstrate that the student understands the concepts? Does the work
demonstrate competence and meet the expectations outlined in the
exercise?

If the answer is \"yes\" to both of the questions, a student passes the
hurdle for that exercise.

If the initial submission does not clear the hurdle, then a second
question is asked: Is there evidence of partial understanding of the
concepts? If the answer to this question is \"Yes\" the student can
exchange one token to attempt a revision of their work. If the answer is
\"No\", the student does not clear the hurdle for this exercise and will
not have the opportunity to revise their work.

## Project

The project is a required hurdle to earn a level A grade. In order to
clear this hurdle, the project must obtain a \"Demonstrates Competence\"
evaluation. There will be opportunities for feedback along the way, but
the final submission will be evaluated. There will be no opportunity for
revising this final submission.

Students need to commit to the project by specifying their team (maximum
of 4 members on a team) by **3-09**. Once the commitment is made, the team
composition is final. Any student who does not submit a team definition
by this date will not be able to pursue the project.

Details on the project rubric will be given out on **2-16**.

## Final Exam

A closed book, closed note, timed final exam will be given on **May 10
(13:00-15:00)**. The exam will be based on a blend of previous quiz questions
and additional questions that pertain to material covered in class.

## Tokens

Each student is provided with three tokens at the beginning of the
semester.

Using Tokens

1.  One token can be used for a one-day extension for an exercise.

2.  One token can be used to revise an exercise that was submitted
    on-time but evaluated as \"Needing Revision\".

3.  Two tokens can be used to request a make-up date for the final exam.

Earning Tokens

1.  Handing in an exercise at least 24 hours before its due date.

2.  Submitting all four exercises on time (or early).

3.  Attempting all 10 quizzes.

Remaining Tokens

Each token that remains unused after **4-27** will be counted as a passed
quiz. *Tokens cannot be exchanged with other students*.

## Policies
### Accomodations
If you are a student with a disability and are in need of
accommodations for this class, please contact Student Ability
Success Center at (619) 594-6473 as soon as possible.  Please know
accommodations are not retroactive, and I cannot provide
accommodations based upon disability until I have received an
accommodation letter from Student Ability Success Center.

### Privacy and Intellectual Property
Student Privacy and Intellectual Property: The Family Educational
Rights and Privacy Act (FERPA) mandates the protection of student
information, including contact information, grades, and graded
assignments. I will use Canvas to communicate with you,
and I will not post grades or leave graded assignments in public
places. Students will be notified at the time of an assignment if
copies of student work will be retained beyond the end of the semester
or used as examples for future students or the wider public. Students
maintain intellectual property rights to work products they create as
part of this course unless they are formally notified otherwise.


### Academic Integrity

The SDSU student academic integrity policy lists violations in detail.
These violations fall into eight broad areas that include but are not
limited to: cheating, fabrication, plagiarism, facilitating academic
misconduct, unauthorized collaboration, interference or sabotage,
non-compliance with research regulations and retaliation. For more
information about the SDSU student academic integrity policy, please see
the following: <https://sacd.sdsu.edu/student-rights/academic-dishonesty>.


### Code of Conduct

As course instructor, I am dedicated to providing a harassment-free
learning experience for all students, regardless of gender, sexual
orientation, disability, physical appearance, body size, race, religion,
or choice of operating system. All course participants are expected to
show respect and courtesy to other students throughout the semester. As
a learning community we do not tolerate harassment of participants in
any form.

-   All communication should be appropriate for a professional audience
    including people of many different backgrounds. Sexual language and
    imagery are not appropriate in this course.

-   Be kind to others. Do not insult or put down other students. Behave
    professionally. Remember that harassment and sexist, racist, or
    exclusionary jokes are not appropriate for this course.

-   Students violating these rules may be asked to leave the course, and
    their violations will be reported to the SDSU administration.

This code of conduct is an adaptation of the [SciPy 2018 Code of
Conduct](https://scipy2018.scipy.org/ehome/299527/648147/index9a04.html).


